// export default [
//   {
//     id: 1,
//     name: "Aino Virtanen",
//     title: "HR Manager",
//     salary: 4200,
//     phone: "040-1234567",
//     email: "aino.virtanen@example.com",
//     animal: "🦉",
//     startDate: "2010-03-15", // 15 години
//     location: "Helsinki",
//     department: "Human Resources",
//     skills: ["Leadership", "Recruitment", "Conflict Resolution"],
//   },
//   {
//     id: 2,
//     name: "Mikko Laine",
//     title: "Software Engineer",
//     salary: 5200,
//     phone: "045-2345678",
//     email: "mikko.laine@example.com",
//     animal: "🐻",
//     startDate: "2015-10-01", // 10 години
//     location: "Tampere",
//     department: "IT Development",
//     skills: ["JavaScript", "React", "Node.js"],
//   },
//   {
//     id: 3,
//     name: "Sari Niemi",
//     title: "UX Designer",
//     salary: 4600,
//     phone: "050-1122334",
//     email: "sari.niemi@example.com",
//     animal: "🐈‍⬛",
//     startDate: "2020-11-25", // 5 години
//     location: "Turku",
//     department: "Design",
//     skills: ["Figma", "User Research", "Accessibility"],
//   },
//   {
//     id: 4,
//     name: "Teemu Korhonen",
//     title: "Project Manager",
//     salary: 5800,
//     phone: "040-9998887",
//     email: "teemu.korhonen@example.com",
//     animal: "🐕",
//     startDate: "2018-06-01", // 7 години
//     location: "Oulu",
//     department: "Management",
//     skills: ["Agile", "Scrum", "Budgeting"],
//   },
//   {
//     id: 5,
//     name: "Laura Miettinen",
//     title: "Marketing Specialist",
//     salary: 3900,
//     phone: "046-2233445",
//     email: "laura.miettinen@example.com",
//     animal: "🐘",
//     startDate: "2024-06-01", // по-малко от 6 месеца
//     location: "Helsinki",
//     department: "Marketing",
//     skills: ["SEO", "Analytics", "Social Media"],
//   },
//   {
//     id: 6,
//     name: "Antti Rantanen",
//     title: "Data Analyst",
//     salary: 4700,
//     phone: "045-6677889",
//     email: "antti.rantanen@example.com",
//     animal: "🦊",
//     startDate: "2019-09-01", // 6 години
//     location: "Espoo",
//     department: "Data Science",
//     skills: ["Python", "SQL", "Power BI"],
//   },
//   {
//     id: 7,
//     name: "Emma Lehtonen",
//     title: "HR Assistant",
//     salary: 3200,
//     phone: "040-5544332",
//     email: "emma.lehtonen@example.com",
//     animal: "🦄",
//     startDate: "2025-08-10", // по-малко от 6 месеца
//     location: "Helsinki",
//     department: "Human Resources",
//     skills: ["Onboarding", "Scheduling", "Team Support"],
//   },
//   {
//     id: 8,
//     name: "Jari Peltonen",
//     title: "Network Engineer",
//     salary: 5000,
//     phone: "041-7788990",
//     email: "jari.peltonen@example.com",
//     animal: "🐢",
//     startDate: "2013-02-20", // 12 години
//     location: "Kuopio",
//     department: "IT Infrastructure",
//     skills: ["Networking", "Security", "Linux"],
//   },
//   {
//     id: 9,
//     name: "Noora Kallio",
//     title: "Recruitment Specialist",
//     salary: 4100,
//     phone: "050-9911223",
//     email: "noora.kallio@example.com",
//     animal: "🐼",
//     startDate: "2015-04-10", // 10 години
//     location: "Helsinki",
//     department: "Human Resources",
//     skills: ["Interviews", "Talent Acquisition", "Branding"],
//   },
//   {
//     id: 10,
//     name: "Ville Hämäläinen",
//     title: "QA Engineer",
//     salary: 4600,
//     phone: "044-2233114",
//     email: "ville.hamalainen@example.com",
//     animal: "🦅",
//     startDate: "2025-06-15", // по-малко от 6 месеца
//     location: "Tampere",
//     department: "Quality Assurance",
//     skills: ["Testing", "Automation", "Cypress"],
//   },
// ];
